services:
  - type: web
    name: sillytavern-luna
    env: docker
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: SILLYTAVERN_HEARTBEATINTERVAL
        value: "30"
    healthCheckPath: /
    healthCheckTimeout: 90
